# a very minimal declarative config file
_format_version: "2.1"
_transform: true

routes:
- name: my-route
  methods:
  - POST
  - OPTIONS
  paths:
  - /api/v1/auth/sign-up
  strip_path: true
  preserve_host: false
  service:
    name: client-api
    url: http://localhost:3002
